### PR TITLE
DM-37259: Accept 200 response code for PUT requests

### PR DESCRIPTION
**Pull request by ptrlv**
## Checklist

- [ ] ran Jenkins
- [ ] added a release note for user-visible changes to `doc/changes`

### CODE REVIEW

**Comment by timj** [comment]
The failure of the build is a bit odd. We haven't had a setup.py in our packages for ages. I wonder if this is a 3.8+setuptools interaction that we don't see on 3.10.

**Comment by ptrlv** [comment]
Is the fix to remove the 3.8 test?

**Comment by timj** [comment]
> Is the fix to remove the 3.8 test?

Try it. @mwittgen might have other thoughts.

**Comment by mwittgen** [comment]
Manually restarted 3.10 build action works. Removing 3.8 and possibly 3.9 might be needed.

**Comment by mwittgen** [comment]
A while ago for broken pip/setuptools versions we pinned pip<22.
The build for 3.8 in this case downgrades pip to 20, for 3.10 to version 21.
Alternatively, unpinning pip might work.

**Comment by mwittgen** [comment]
I'll have a look. This is likely causing problem in other repos as well.

**Comment by timj** [comment]
If we are going to drop 3.8 from the build please remember to update pyproject.toml accordingly.

**Comment by mwittgen** [comment]
Fixed in: [tickets/DM-37333](https://github.com/lsst/resources/tree/tickets/DM-37333)

**Comment by ptrlv** [comment]
Please check this as 3.8 is still failing. Not sure what action is needed.

**Comment by timj** [comment]
@ptrlv I've rebased so we can see whether that fixes the build problem. You will have to take that into account if you pull the changes locally.

**Pull request merged**
